server:
  port: 8080

ranked:
  host:
    backend: backend
zuul:
  routes:
    command:
      path: /command/**
      url: http://${ranked.host.backend}:8081/command
    view:
      path: /view/**
      url: http://${ranked.host.backend}:8081/view
