sudo: false
language: java
jdk:
  - oraclejdk8
install: true
before_install:
  - chmod +x mvnw
cache:
  directories:
    - $HOME/.m2
script: ./mvnw clean verify
after_success:
  - bash <(curl -s https://codecov.io/bash)
