server:
  port: 8081

spring:
  application:
    name: ranked
  datasource:
    url: jdbc:h2:tcp://localhost:9092/mem:ranked
    username: sa
    password: sa
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: false

ranked:
  score.match: 2 # best of three
  score.set: 6   # play to 6
