spring:
  application:
    name: ranked-command-service
  datasource:
    url: jdbc:h2:tcp://localhost:9092/mem:${spring.application.name}
    username: sa
    password: sa
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: false
